name: test
on:
  pull_request:
    branches:
      - main
jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3.1.3
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run test
